### ISSUE TITLE
[Feature Request] Add constructor for data structure

### ISSUE THREAD

**Issue by Zxilly** [sam20908/lc-cpp#2]
LinkNode and TreeNode in leetcode has correspond constructor like

```
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
```

Is that possible to add them?

**Comment by Zxilly** [comment]
A possible implementation like

```cpp
  ListNode() = default;
  ListNode(int x) : val(x) {}
  ListNode(int x, ListNode *next) : val(x), next(next) {}
  ~ListNode() {
    delete next;
  }
```

**Comment by sam20908** [comment]
Hello @Zxilly , they have been predefined in `parser.hpp` (which is included if you compile locally with `-DLC_LOCAL`). The reason I didn't put them in the main template file is because LeetCode defiles it themselves and I'm afraid the code will get redefinition error for those types.

See https://github.com/sam20908/competitive-programming/blob/f400cb89707b7cb9b65dad7158e4c0bf73d93c92/leetcode/parser.hpp#L6

**Comment by celonymire** [comment]
Yes I'll add them

**Comment by celonymire** [comment]
Added
